-- Autogenerated with
-- 		local out = "" for i, child in game.Selection:Get()[1]:GetChildren() do if child:IsA("ImageButton") then out ..= `["{child.BackgroundColor3:ToHex()}"] = true,\n` end end print(out)
local PrimaryColors: { [string]: boolean } = {
	["d7c59a"] = true,
	["506d54"] = true,
	["e29b40"] = true,
	["edeaea"] = true,
	["6e99ca"] = true,
	["e0b2d0"] = true,
	["464646"] = true,
	["cc8e69"] = true,
	["6c584b"] = true,
	["777af3"] = true,
}

local AccentColors: { [string]: boolean } = {
	["d7c59a"] = true,
	["506d54"] = true,
	["e29b40"] = true,
	["edeaea"] = true,
	["6e99ca"] = true,
	["e0b2d0"] = true,
	["464646"] = true,
	["cc8e69"] = true,
	["6c584b"] = true,
	["777af3"] = true,
}

local Config = {
	StandTag = "DisplayStandSpot",
	NoBobTag = "NoBob",
	NoSpinTag = "NoSpin",
	ScaleTag = "Scale",

	PrimaryColorTag = "PrimaryColor",
	AccentColorTag = "AccentColor",
	TextureTag = "Texture",

	StandRotationSpeed = math.rad(75),
	StandBobSpeed = 0.2,
	DefaultScale = 2.5,

	-- Won't allow you to create new places if you exceed this number
	MaxPlaces = 20,

	-- Place names can't be longer than this
	MaxPlaceNameLength = 20,

	PrimaryColors = PrimaryColors,
	AccentColors = AccentColors,
	DefaultPrimaryColor = Color3.fromRGB(215, 197, 154),
	DefaultAccentColor = Color3.fromRGB(215, 197, 154),
}

assert(PrimaryColors[Config.DefaultPrimaryColor:ToHex()], "Default primary color was not a valid color")
assert(AccentColors[Config.DefaultAccentColor:ToHex()], "Default accent color was not a valid color")

return Config
