local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Guard = require(ReplicatedStorage.Packages.Guard)
local Red = require(ReplicatedStorage.Packages.Red)
return Red.Event("Showcase_PurchaseAsset", function(assetId)
	return Guard.Number(assetId)
end)
